### ISSUE TITLE
Gosford scraper is not collecting data

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/multiple_icon#4]
````
Collecting feed data for gosford...
/app/vendor/bundle/ruby/2.5.0/bundler/gems/icon_scraper-f285e441f6ce/lib/icon_scraper.rb:38:in `scrape_with_params'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/icon_scraper-f285e441f6ce/lib/icon_scraper.rb:17:in `scrape'
scraper.rb:10:in `block in scrape'
scraper.rb:6:in `each'
scraper.rb:6:in `scrape'
scraper.rb:27:in `<main>'
````

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1othh)

**Comment by jamezpolley** [comment]
This has been fixed by @mlandauer in https://github.com/planningalerts-scrapers/icon_scraper/commit/0b1ba739b5a6bdb631485410d9bf64c7f3b10324 and 8546d6eedb48904e5fe1a917b3e3db9bee4d8c63
